### ISSUE TITLE
Initial Tag

### ISSUE THREAD

**Issue by reiz** [Labs64/swid-maven-plugin#1]
This project was submitted at https://www.versioneye.com. To be able to track this project correctly at VersionEye a tag is required. Why not create an initial tag? For example `0.1.0-RC1`. That's even conform with semantic versioning ;-)

**Comment by r-brown** [comment]
Hi Robert,

Thank you for your tip.
New tag [0.1.0-alpha.1](https://github.com/Labs64/swid-maven-plugin/releases/tag/0.1.0-alpha.1) has been created.

Best Regards,
  R.Brown

**Comment by reiz** [comment]
+1
